### ISSUE TITLE
Document instructions on how to deploy actions and services in another region

### ISSUE THREAD

**Issue by l2fprod** [IBM-Cloud/serverless-followupapp-ios#1]
If the developer wants to deploy the app in any IBM Cloud region, the following need to be updated in the app:

* in https://github.com/IBM-Cloud/serverless-followupapp-ios/blob/master/followupapp/FollowUpappid/AppDelegate.swift#L28, the location of the mobile push service should be updated using one of the constants under BMSClient.Region. However this can only happen after https://github.com/apache/incubator-openwhisk-package-pushnotifications/issues/85 is fixed - this is likely to require changes in deploy.sh to pass the `url` from the credentials

* in https://github.com/IBM-Cloud/serverless-followupapp-ios/blob/master/followupapp/FollowUpappid/BMSCredentials.plist the Cloud Functions host should be updated - basically replacing `ng` with the region where Cloud Functions is deployed `eu-de`, `eu-gb`

**Comment by l2fprod** [comment]
@VidyasagarMSC in the meantime we should change AppDelegate.swift to point to US South - currently it points to Sydney.

**Comment by VidyasagarMSC** [comment]
@l2fprod The above change is in place.
