### ISSUE TITLE
Please set apiHost for Mobile Push when deploying the wsk actions

### ISSUE THREAD

**Issue by rmey** [IBM-Cloud/serverless-followupapp-ios#4]
From the Push Serverless Package doc, otherwise it won't fly in other regions.
` @param {string} apiHost - An optional string that specifies the API host.  The default is 'mobile.ng.bluemix.net'.  Eg : -p apiHost "mobile.eu-gb.bluemix.net".`

**Comment by rmey** [comment]
in deploy.sh I added
`ibmcloud wsk package bind /whisk.system/pushnotifications \
    $PACKAGE_NAME-push \
    -p appId $PUSH_APP_GUID \
    -p appSecret $PUSH_APP_SECRET \
    -p apiHost $PUSH_APP_API_HOST`
in env.local/template I added
`PUSH_APP_API_HOST=imfpush.eu-de.bluemix.net`

**Comment by VidyasagarMSC** [comment]
Fixed
